"""finitura_database_v1

Revision ID: 0b35beccd144
Revises: 
Create Date: 2026-01-16 15:05:23.882180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b35beccd144'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('ricorrenze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('frequenza', sa.String(), nullable=False),
    sa.Column('prossima_esecuzione', sa.Date(), nullable=False),
    sa.Column('attiva', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conto_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorie.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conto_id'], ['conti.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ricorrenze_id'), 'ricorrenze', ['id'], unique=False)
    op.create_table('sottocategorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sottocategorie_id'), 'sottocategorie', ['id'], unique=False)
    op.drop_constraint(op.f('categorie_parent_id_fkey'), 'categorie', type_='foreignkey')
    op.drop_column('categorie', 'parent_id')
    op.add_column('conti', sa.Column('saldo', sa.Float(), nullable=False))
    op.add_column('conti', sa.Column('ricarica_automatica', sa.Boolean(), nullable=True))
    op.add_column('conti', sa.Column('budget_obiettivo', sa.Float(), nullable=True))
    op.add_column('conti', sa.Column('soglia_minima', sa.Float(), nullable=True))
    op.add_column('conti', sa.Column('conto_sorgente_id', sa.Integer(), nullable=True))
    op.add_column('conti', sa.Column('frequenza_controllo', sa.String(), nullable=True))
    op.add_column('conti', sa.Column('prossimo_controllo', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'conti', 'conti', ['conto_sorgente_id'], ['id'])
    op.drop_column('conti', 'tipo')
    op.add_column('investimenti', sa.Column('ticker', sa.String(), nullable=True))
    op.add_column('investimenti', sa.Column('prezzo_attuale', sa.Float(), nullable=True))
    op.add_column('investimenti', sa.Column('data_ultimo_aggiornamento', sa.Date(), nullable=True))
    op.create_index(op.f('ix_investimenti_ticker'), 'investimenti', ['ticker'], unique=False)
    op.drop_constraint(op.f('storico_investimenti_investimento_id_fkey'), 'storico_investimenti', type_='foreignkey')
    op.create_foreign_key(None, 'storico_investimenti', 'investimenti', ['investimento_id'], ['id'], ondelete='CASCADE')
    op.add_column('transazioni', sa.Column('sottocategoria_id', sa.Integer(), nullable=True))
    op.add_column('transazioni', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('transazioni_categoria_id_fkey'), 'transazioni', type_='foreignkey')
    op.drop_constraint(op.f('transazioni_conto_id_fkey'), 'transazioni', type_='foreignkey')
    op.create_foreign_key(None, 'transazioni', 'sottocategorie', ['sottocategoria_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transazioni', 'tags', ['tag_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transazioni', 'categorie', ['categoria_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transazioni', 'conti', ['conto_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('total_budget', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_budget')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'transazioni', type_='foreignkey')
    op.drop_constraint(None, 'transazioni', type_='foreignkey')
    op.drop_constraint(None, 'transazioni', type_='foreignkey')
    op.drop_constraint(None, 'transazioni', type_='foreignkey')
    op.create_foreign_key(op.f('transazioni_conto_id_fkey'), 'transazioni', 'conti', ['conto_id'], ['id'])
    op.create_foreign_key(op.f('transazioni_categoria_id_fkey'), 'transazioni', 'categorie', ['categoria_id'], ['id'])
    op.drop_column('transazioni', 'tag_id')
    op.drop_column('transazioni', 'sottocategoria_id')
    op.drop_constraint(None, 'storico_investimenti', type_='foreignkey')
    op.create_foreign_key(op.f('storico_investimenti_investimento_id_fkey'), 'storico_investimenti', 'investimenti', ['investimento_id'], ['id'])
    op.drop_index(op.f('ix_investimenti_ticker'), table_name='investimenti')
    op.drop_column('investimenti', 'data_ultimo_aggiornamento')
    op.drop_column('investimenti', 'prezzo_attuale')
    op.drop_column('investimenti', 'ticker')
    op.add_column('conti', sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conti', type_='foreignkey')
    op.drop_column('conti', 'prossimo_controllo')
    op.drop_column('conti', 'frequenza_controllo')
    op.drop_column('conti', 'conto_sorgente_id')
    op.drop_column('conti', 'soglia_minima')
    op.drop_column('conti', 'budget_obiettivo')
    op.drop_column('conti', 'ricarica_automatica')
    op.drop_column('conti', 'saldo')
    op.add_column('categorie', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('categorie_parent_id_fkey'), 'categorie', 'categorie', ['parent_id'], ['id'])
    op.drop_index(op.f('ix_sottocategorie_id'), table_name='sottocategorie')
    op.drop_table('sottocategorie')
    op.drop_index(op.f('ix_ricorrenze_id'), table_name='ricorrenze')
    op.drop_table('ricorrenze')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
