"""add_last_import_to_conti

Revision ID: 15bf685f2dc3
Revises: 6a363d2c3e40
Create Date: 2026-02-28 17:27:44.570732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bf685f2dc3'
down_revision: Union[str, Sequence[str], None] = '6a363d2c3e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conti', sa.Column('lastImport', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conti', 'lastImport')
    # ### end Alembic commands ###
