"""aggiunto storico investimenti e proprietà calcolate

Revision ID: 38e99e834af6
Revises: 5fe513ca1265
Create Date: 2026-02-03 18:06:58.071677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e99e834af6'
down_revision: Union[str, Sequence[str], None] = '5fe513ca1265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
