"""cambio tipo data transazione in Date

Revision ID: 3d79b8af4a2f
Revises: 38e99e834af6
Create Date: 2026-02-10 11:32:16.079976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d79b8af4a2f'
down_revision: Union[str, Sequence[str], None] = '38e99e834af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transazioni_id'), table_name='transazioni')
    op.drop_table('transazioni')
    op.drop_index(op.f('ix_ricorrenze_id'), table_name='ricorrenze')
    op.drop_table('ricorrenze')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_categorie_id'), table_name='categorie')
    op.drop_table('categorie')
    op.drop_index(op.f('ix_sottocategorie_id'), table_name='sottocategorie')
    op.drop_table('sottocategorie')
    op.drop_index(op.f('ix_storico_investimenti_id'), table_name='storico_investimenti')
    op.drop_table('storico_investimenti')
    op.drop_index(op.f('ix_conti_id'), table_name='conti')
    op.drop_table('conti')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_investimenti_id'), table_name='investimenti')
    op.drop_index(op.f('ix_investimenti_isin'), table_name='investimenti')
    op.drop_index(op.f('ix_investimenti_ticker'), table_name='investimenti')
    op.drop_table('investimenti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investimenti',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('isin', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nome_titolo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prezzo_attuale', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('data_ultimo_aggiornamento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('creationDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lastUpdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('investimenti_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('investimenti_pkey'))
    )
    op.create_index(op.f('ix_investimenti_ticker'), 'investimenti', ['ticker'], unique=False)
    op.create_index(op.f('ix_investimenti_isin'), 'investimenti', ['isin'], unique=False)
    op.create_index(op.f('ix_investimenti_id'), 'investimenti', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('creationDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lastUpdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('conti',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('saldo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ricarica_automatica', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('budget_obiettivo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('soglia_minima', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('conto_sorgente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('frequenza_controllo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prossimo_controllo', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creationDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lastUpdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conto_sorgente_id'], ['conti.id'], name=op.f('conti_conto_sorgente_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conti_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conti_pkey'))
    )
    op.create_index(op.f('ix_conti_id'), 'conti', ['id'], unique=False)
    op.create_table('storico_investimenti',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('investimento_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('quantita', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('prezzo_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valore_attuale', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('creationDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lastUpdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['investimento_id'], ['investimenti.id'], name=op.f('storico_investimenti_investimento_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('storico_investimenti_pkey'))
    )
    op.create_index(op.f('ix_storico_investimenti_id'), 'storico_investimenti', ['id'], unique=False)
    op.create_table('sottocategorie',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creationDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lastUpdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorie.id'], name=op.f('sottocategorie_categoria_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sottocategorie_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sottocategorie_pkey'))
    )
    op.create_index(op.f('ix_sottocategorie_id'), 'sottocategorie', ['id'], unique=False)
    op.create_table('categorie',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creationDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lastUpdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('categorie_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('categorie_pkey'))
    )
    op.create_index(op.f('ix_categorie_id'), 'categorie', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creationDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lastUpdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tags_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey'))
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('ricorrenze',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('importo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('frequenza', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prossima_esecuzione', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('attiva', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creationDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lastUpdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorie.id'], name=op.f('ricorrenze_categoria_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conto_id'], ['conti.id'], name=op.f('ricorrenze_conto_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('ricorrenze_tag_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ricorrenze_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ricorrenze_pkey'))
    )
    op.create_index(op.f('ix_ricorrenze_id'), 'ricorrenze', ['id'], unique=False)
    op.create_table('transazioni',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('importo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('descrizione', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sottocategoria_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_transaction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creationDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lastUpdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorie.id'], name=op.f('transazioni_categoria_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conto_id'], ['conti.id'], name=op.f('transazioni_conto_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_transaction_id'], ['transazioni.id'], name=op.f('transazioni_parent_transaction_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sottocategoria_id'], ['sottocategorie.id'], name=op.f('transazioni_sottocategoria_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('transazioni_tag_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('transazioni_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transazioni_pkey'))
    )
    op.create_index(op.f('ix_transazioni_id'), 'transazioni', ['id'], unique=False)
    # ### end Alembic commands ###
