"""add split transaction

Revision ID: 4a9299ada80f
Revises: c86ece7f1bf0
Create Date: 2026-06-14 15:57:26.388578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9299ada80f'
down_revision: Union[str, Sequence[str], None] = 'c86ece7f1bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transaction_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conto_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('importo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('imported_transaction_id', sa.Integer(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conto_id'], ['conti.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['imported_transaction_id'], ['transazioni.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transaction_proposals_external_id'), 'bank_transaction_proposals', ['external_id'], unique=False)
    op.create_index(op.f('ix_bank_transaction_proposals_id'), 'bank_transaction_proposals', ['id'], unique=False)
    op.add_column('conti', sa.Column('bank_connector_provider', sa.String(), nullable=True))
    op.add_column('conti', sa.Column('bank_connector_account_id', sa.String(), nullable=True))
    op.add_column('conti', sa.Column('bank_connector_institution_id', sa.String(), nullable=True))
    op.add_column('conti', sa.Column('bank_connector_client_id', sa.String(), nullable=True))
    op.add_column('conti', sa.Column('bank_connector_secret', sa.String(), nullable=True))
    op.add_column('conti', sa.Column('bank_connector_access_token', sa.String(), nullable=True))
    op.add_column('conti', sa.Column('bank_connector_refresh_token', sa.String(), nullable=True))
    op.add_column('conti', sa.Column('bank_connector_last_sync', sa.DateTime(), nullable=True))
    op.add_column('conti', sa.Column('bank_connector_last_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conti', 'bank_connector_last_error')
    op.drop_column('conti', 'bank_connector_last_sync')
    op.drop_column('conti', 'bank_connector_refresh_token')
    op.drop_column('conti', 'bank_connector_access_token')
    op.drop_column('conti', 'bank_connector_secret')
    op.drop_column('conti', 'bank_connector_client_id')
    op.drop_column('conti', 'bank_connector_institution_id')
    op.drop_column('conti', 'bank_connector_account_id')
    op.drop_column('conti', 'bank_connector_provider')
    op.drop_index(op.f('ix_bank_transaction_proposals_id'), table_name='bank_transaction_proposals')
    op.drop_index(op.f('ix_bank_transaction_proposals_external_id'), table_name='bank_transaction_proposals')
    op.drop_table('bank_transaction_proposals')
    # ### end Alembic commands ###
