"""Initial migration

Revision ID: 5fe513ca1265
Revises: 
Create Date: 2026-01-28 17:41:35.315733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe513ca1265'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorie_id'), 'categorie', ['id'], unique=False)
    op.create_table('conti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('ricarica_automatica', sa.Boolean(), nullable=True),
    sa.Column('budget_obiettivo', sa.Float(), nullable=True),
    sa.Column('soglia_minima', sa.Float(), nullable=True),
    sa.Column('conto_sorgente_id', sa.Integer(), nullable=True),
    sa.Column('frequenza_controllo', sa.String(), nullable=True),
    sa.Column('prossimo_controllo', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conto_sorgente_id'], ['conti.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conti_id'), 'conti', ['id'], unique=False)
    op.create_table('investimenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('nome_titolo', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prezzo_attuale', sa.Float(), nullable=True),
    sa.Column('data_ultimo_aggiornamento', sa.Date(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investimenti_id'), 'investimenti', ['id'], unique=False)
    op.create_index(op.f('ix_investimenti_isin'), 'investimenti', ['isin'], unique=False)
    op.create_index(op.f('ix_investimenti_ticker'), 'investimenti', ['ticker'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('ricorrenze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('frequenza', sa.String(), nullable=False),
    sa.Column('prossima_esecuzione', sa.Date(), nullable=False),
    sa.Column('attiva', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conto_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorie.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conto_id'], ['conti.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ricorrenze_id'), 'ricorrenze', ['id'], unique=False)
    op.create_table('sottocategorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sottocategorie_id'), 'sottocategorie', ['id'], unique=False)
    op.create_table('storico_investimenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investimento_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('quantita', sa.Float(), nullable=True),
    sa.Column('prezzo_unitario', sa.Float(), nullable=True),
    sa.Column('valore_attuale', sa.Float(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investimento_id'], ['investimenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storico_investimenti_id'), 'storico_investimenti', ['id'], unique=False)
    op.create_table('transazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('descrizione', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conto_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('sottocategoria_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('parent_transaction_id', sa.Integer(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorie.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conto_id'], ['conti.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_transaction_id'], ['transazioni.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sottocategoria_id'], ['sottocategorie.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transazioni_id'), 'transazioni', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transazioni_id'), table_name='transazioni')
    op.drop_table('transazioni')
    op.drop_index(op.f('ix_storico_investimenti_id'), table_name='storico_investimenti')
    op.drop_table('storico_investimenti')
    op.drop_index(op.f('ix_sottocategorie_id'), table_name='sottocategorie')
    op.drop_table('sottocategorie')
    op.drop_index(op.f('ix_ricorrenze_id'), table_name='ricorrenze')
    op.drop_table('ricorrenze')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_investimenti_ticker'), table_name='investimenti')
    op.drop_index(op.f('ix_investimenti_isin'), table_name='investimenti')
    op.drop_index(op.f('ix_investimenti_id'), table_name='investimenti')
    op.drop_table('investimenti')
    op.drop_index(op.f('ix_conti_id'), table_name='conti')
    op.drop_table('conti')
    op.drop_index(op.f('ix_categorie_id'), table_name='categorie')
    op.drop_table('categorie')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
