"""add_last_import_to_categories_subcategories

Revision ID: 6a363d2c3e40
Revises: f98202fd9632
Create Date: 2026-02-28 17:16:26.622508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a363d2c3e40'
down_revision: Union[str, Sequence[str], None] = 'f98202fd9632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorie', sa.Column('lastImport', sa.DateTime(), nullable=True))
    op.add_column('sottocategorie', sa.Column('lastImport', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sottocategorie', 'lastImport')
    op.drop_column('categorie', 'lastImport')
    # ### end Alembic commands ###
