"""rimosso solo_rimborso

Revision ID: 8abc975b8af6
Revises: 4eb0483f9242
Create Date: 2026-03-06 16:52:00.743683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abc975b8af6'
down_revision: Union[str, Sequence[str], None] = '4eb0483f9242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorie', 'solo_rimborso')
    op.drop_column('sottocategorie', 'solo_rimborso')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sottocategorie', sa.Column('solo_rimborso', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('categorie', sa.Column('solo_rimborso', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
