"""add debiti

Revision ID: 8c711d33ea7b
Revises: 9c4d696cc22d
Create Date: 2026-06-14 14:08:00.588740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c711d33ea7b'
down_revision: Union[str, Sequence[str], None] = '9c4d696cc22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debiti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ammontare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('residuo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conto_id', sa.Integer(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conto_id'], ['conti.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debiti_id'), 'debiti', ['id'], unique=False)
    op.add_column('transazioni', sa.Column('debito_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transazioni', 'debiti', ['debito_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transazioni', type_='foreignkey')
    op.drop_column('transazioni', 'debito_id')
    op.drop_index(op.f('ix_debiti_id'), table_name='debiti')
    op.drop_table('debiti')
    # ### end Alembic commands ###
