"""aggiunta token_version per invalidazione JWT

Revision ID: 9c4d696cc22d
Revises: d0ae21051f0a
Create Date: 2026-04-01 22:39:37.688663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c4d696cc22d"
down_revision: Union[str, Sequence[str], None] = "d0ae21051f0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Aggiungi prima la colonna permettendo i valori nulli
    op.add_column("users", sa.Column("token_version", sa.Integer(), nullable=True))

    # Popola le righe esistenti con il valore di default (1)
    op.execute("UPDATE users SET token_version = 1")

    # Modifica la colonna per non permettere più valori nulli
    op.alter_column("users", "token_version", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token_version")
    # ### end Alembic commands ###
