"""improved rimborsi

Revision ID: 9cd85e955956
Revises: 15bf685f2dc3
Create Date: 2026-03-04 15:33:23.514123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd85e955956'
down_revision: Union[str, Sequence[str], None] = '15bf685f2dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transazioni', sa.Column('importo_netto', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transazioni', 'importo_netto')
    # ### end Alembic commands ###
