"""aggiornato utilizzo delle ricorrenze con userId e sottocategoriaId

Revision ID: be63eea1dd82
Revises: 305182ffc4a6
Create Date: 2026-02-11 12:53:09.132043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be63eea1dd82'
down_revision: Union[str, Sequence[str], None] = '305182ffc4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ricorrenze', sa.Column('sottocategoria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ricorrenze', 'sottocategorie', ['sottocategoria_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ricorrenze', type_='foreignkey')
    op.drop_column('ricorrenze', 'sottocategoria_id')
    # ### end Alembic commands ###
