"""incluso il colore dei conti

Revision ID: e644d70020db
Revises: dd8b6937e751
Create Date: 2026-02-10 18:28:07.393787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e644d70020db'
down_revision: Union[str, Sequence[str], None] = 'dd8b6937e751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conti', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conti', 'color')
    # ### end Alembic commands ###
