"""add_type_flags_to_categories

Revision ID: f98202fd9632
Revises: be63eea1dd82
Create Date: 2026-02-28 16:59:54.481811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98202fd9632'
down_revision: Union[str, Sequence[str], None] = 'be63eea1dd82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorie', sa.Column('solo_entrata', sa.Boolean(), nullable=True))
    op.add_column('categorie', sa.Column('solo_uscita', sa.Boolean(), nullable=True))
    op.add_column('categorie', sa.Column('solo_rimborso', sa.Boolean(), nullable=True))
    op.add_column('conti', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('sottocategorie', sa.Column('solo_entrata', sa.Boolean(), nullable=True))
    op.add_column('sottocategorie', sa.Column('solo_uscita', sa.Boolean(), nullable=True))
    op.add_column('sottocategorie', sa.Column('solo_rimborso', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sottocategorie', 'solo_rimborso')
    op.drop_column('sottocategorie', 'solo_uscita')
    op.drop_column('sottocategorie', 'solo_entrata')
    op.drop_column('conti', 'default')
    op.drop_column('categorie', 'solo_rimborso')
    op.drop_column('categorie', 'solo_uscita')
    op.drop_column('categorie', 'solo_entrata')
    # ### end Alembic commands ###
